version: '3.8'

services:
  scraper:
    build: .
    container_name: crypto-scraper
    restart: unless-stopped
    environment:
      # Supabase configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}

      # Scraper configuration
      - SCRAPER_INTERVAL_MINUTES=${SCRAPER_INTERVAL_MINUTES:-60}
      - SCRAPER_CRYPTOS=${SCRAPER_CRYPTOS:-BTC,ETH}

      # Playwright configuration
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    volumes:
      # Mount logs directory (optional, for persistence)
      - ./logs:/app/logs
    mem_limit: 1g
    mem_reservation: 512m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
